# Adapted from:
# https://github.com/VaultVulp/gp-docker-action#complete-workflow-example
name: Build and publish tag

on:
  push:
    tags:
    - "*"

jobs:
  build-and-publish-image:
    if: github.repository == 'mitre/growthcleanr'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and publish Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: gcr-image
          extract-git-tag: true
